name: CI

on:
  schedule:
    - cron: '12 3 10 * *'
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    container:
      image: practicalscheme/gauche
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup package
        run: |
      - name: Setup gauche submodule packages
        run: |
          set -eu;
          cd packages/.modules;
          find . -type d -mindepth 1 -maxdepth 1 | sort | while read pkg; do
            echo "Installing ${pkg} in sub process";
            (
              cd "${pkg}";
              ./configure;
              make install;
            );
          done
      - name: CI
        run: ./run-ci.sh
